### PR TITLE
add EvtExportLog function to wineventlog

### PR DESCRIPTION
**Pull request by jfut**
Hi, thanks for this useful library!

This PR to add EvtExportLog function to wineventlog.
https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtexportlog

I would appreciate it if you could accept this PR.

### CODE REVIEW

**Review by kris-watts-gravwell — APPROVED** [review]
Lgtm

**Review by kris-watts-gravwell — APPROVED** [review]
LGTM

**Comment by jfut** [comment]
Thanks!

**Comment by kris-watts-gravwell** [comment]
Thank you for the PR.  It was well documented and easy to read!

**Pull request merged**
